astra_db:
  collection_name: "chatbotecomm"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 2

llm:
  provider: "openai"
  model_name: "gpt-4o-mini"

