name: Build and push Image to ECR and deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-push-ecr-image:
    name: Build and push to Amazon ECR
    run-on: ubuntu-latest

    steps:
    - name: check out the code 
      uses: actions/checkout@v2

    - name: Install Utitlities
      run: 
        sudo apt-get update
        sudo apt-get install -y jq unzip

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: customer-support-system
        IMAGE_TAG: latest

      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        